<?php

/**
 * @file
 * Examples demonstrating how to implement and invoke hooks.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\yse_cas_event_subscribers\Form\BulkLookupAddCasUsers;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function yse_cas_event_subscribers_form_bulk_add_cas_users_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['submit']['#submit'][] = '\Drupal\yse_cas_event_subscribers\Form\BulkLookupAddCasUsers::parseLines';
}

/**
 * Implements hook_help().
 */
function yse_cas_event_subscribers_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name == 'help.page.yse_cas_event_subscribers') {
    $text = file_get_contents(__DIR__ . '/README.md');
    if (!Drupal::moduleHandler()->moduleExists('markdown')) {
      return '<pre>' . $text . '</pre>';
    }
    else {
      /** @var \Drupal\markdown\PluginManager\ParserManagerInterface $parser_manager */
      $parser_manager = \Drupal::service('plugin.manager.markdown.parser');
      $parser = $parser_manager->getDefaultParser([
        'render_strategy' => ['type' => 'none'],
      ]);
      return $parser->parse($text);
    }
  }
  return NULL;
}
